/*flexberryautogenerated="true"*/
namespace IIS.Product_47130
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class РабочаяГруппаL : BaseListForm<РабочаяГруппа>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public РабочаяГруппаL() : base(РабочаяГруппа.Views.РабочаяГруппаL)
        {
            EditPage = РабочаяГруппаE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/RabochayaGruppa/RabochayaGruppaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
