/*flexberryautogenerated="true"*/
namespace IIS.Product_47130
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class ЭкскурсияL : BaseListForm<Экскурсия>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public ЭкскурсияL() : base(Экскурсия.Views.ЭкскурсияL)
        {
            EditPage = ЭкскурсияE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Ekskursiya/EkskursiyaL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
