//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Документ.
    /// </summary>
    // *** Start programmer edit section *** (Документ CustomAttributes)

    // *** End programmer edit section *** (Документ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокументE", new string[] {
            "Путь as \'Путь\'",
            "Название as \'Название\'",
            "Расширение as \'Расширение\'",
            "Собрание as \'Собрание\'",
            "Собрание.Тема as \'Тема\'"})]
    [View("ДокументL", new string[] {
            "Путь as \'Путь\'",
            "Название as \'Название\'",
            "Расширение as \'Расширение\'",
            "Собрание.Тема as \'Тема\'"})]
    public class Документ : ICSSoft.STORMNET.DataObject
    {
        
        private string fПуть;
        
        private string fНазвание;
        
        private string fРасширение;
        
        private IIS.Product_47130.Собрание fСобрание;
        
        // *** Start programmer edit section *** (Документ CustomMembers)

        // *** End programmer edit section *** (Документ CustomMembers)

        
        /// <summary>
        /// Путь.
        /// </summary>
        // *** Start programmer edit section *** (Документ.Путь CustomAttributes)

        // *** End programmer edit section *** (Документ.Путь CustomAttributes)
        [StrLen(255)]
        public virtual string Путь
        {
            get
            {
                // *** Start programmer edit section *** (Документ.Путь Get start)

                // *** End programmer edit section *** (Документ.Путь Get start)
                string result = this.fПуть;
                // *** Start programmer edit section *** (Документ.Путь Get end)

                // *** End programmer edit section *** (Документ.Путь Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Документ.Путь Set start)

                // *** End programmer edit section *** (Документ.Путь Set start)
                this.fПуть = value;
                // *** Start programmer edit section *** (Документ.Путь Set end)

                // *** End programmer edit section *** (Документ.Путь Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Документ.Название CustomAttributes)

        // *** End programmer edit section *** (Документ.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Документ.Название Get start)

                // *** End programmer edit section *** (Документ.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Документ.Название Get end)

                // *** End programmer edit section *** (Документ.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Документ.Название Set start)

                // *** End programmer edit section *** (Документ.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Документ.Название Set end)

                // *** End programmer edit section *** (Документ.Название Set end)
            }
        }
        
        /// <summary>
        /// Расширение.
        /// </summary>
        // *** Start programmer edit section *** (Документ.Расширение CustomAttributes)

        // *** End programmer edit section *** (Документ.Расширение CustomAttributes)
        [StrLen(255)]
        public virtual string Расширение
        {
            get
            {
                // *** Start programmer edit section *** (Документ.Расширение Get start)

                // *** End programmer edit section *** (Документ.Расширение Get start)
                string result = this.fРасширение;
                // *** Start programmer edit section *** (Документ.Расширение Get end)

                // *** End programmer edit section *** (Документ.Расширение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Документ.Расширение Set start)

                // *** End programmer edit section *** (Документ.Расширение Set start)
                this.fРасширение = value;
                // *** Start programmer edit section *** (Документ.Расширение Set end)

                // *** End programmer edit section *** (Документ.Расширение Set end)
            }
        }
        
        /// <summary>
        /// Документ.
        /// </summary>
        // *** Start programmer edit section *** (Документ.Собрание CustomAttributes)

        // *** End programmer edit section *** (Документ.Собрание CustomAttributes)
        public virtual IIS.Product_47130.Собрание Собрание
        {
            get
            {
                // *** Start programmer edit section *** (Документ.Собрание Get start)

                // *** End programmer edit section *** (Документ.Собрание Get start)
                IIS.Product_47130.Собрание result = this.fСобрание;
                // *** Start programmer edit section *** (Документ.Собрание Get end)

                // *** End programmer edit section *** (Документ.Собрание Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Документ.Собрание Set start)

                // *** End programmer edit section *** (Документ.Собрание Set start)
                this.fСобрание = value;
                // *** Start programmer edit section *** (Документ.Собрание Set end)

                // *** End programmer edit section *** (Документ.Собрание Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокументE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументE", typeof(IIS.Product_47130.Документ));
                }
            }
            
            /// <summary>
            /// "ДокументL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокументL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокументL", typeof(IIS.Product_47130.Документ));
                }
            }
        }
    }
}
