//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заявка на экскурсию.
    /// </summary>
    // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию CustomAttributes)

    // *** End programmer edit section *** (ЗаявкаНаЭкскурсию CustomAttributes)
    [AutoAltered()]
    [Caption("Заявка на экскурсию")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаявкаНаЭкскурсиюE", new string[] {
            "Дата as \'Дата\'",
            "Количество as \'Количество\'",
            "Экскурсия as \'Экскурсия\'",
            "Экскурсия.Дата as \'Дата\'",
            "Университет as \'Университет\'",
            "Университет.Название as \'Название\'"})]
    [View("ЗаявкаНаЭкскурсиюL", new string[] {
            "Дата as \'Дата\'",
            "Количество as \'Количество\'",
            "Экскурсия.Дата as \'Дата\'",
            "Университет.Название as \'Название\'"})]
    public class ЗаявкаНаЭкскурсию : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private byte fКоличество;
        
        private IIS.Product_47130.Экскурсия fЭкскурсия;
        
        private IIS.Product_47130.Университет fУниверситет;
        
        // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию CustomMembers)

        // *** End programmer edit section *** (ЗаявкаНаЭкскурсию CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Дата Get start)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Дата Get end)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Дата Set start)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Дата Set end)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Дата Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Количество CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Количество CustomAttributes)
        public virtual byte Количество
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Количество Get start)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Количество Get start)
                byte result = this.fКоличество;
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Количество Get end)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Количество Set start)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Количество Set end)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Количество Set end)
            }
        }
        
        /// <summary>
        /// Заявка на экскурсию.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия CustomAttributes)
        public virtual IIS.Product_47130.Экскурсия Экскурсия
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия Get start)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия Get start)
                IIS.Product_47130.Экскурсия result = this.fЭкскурсия;
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия Get end)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия Set start)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия Set start)
                this.fЭкскурсия = value;
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия Set end)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Экскурсия Set end)
            }
        }
        
        /// <summary>
        /// Заявка на экскурсию.
        /// </summary>
        // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Университет CustomAttributes)

        // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Университет CustomAttributes)
        public virtual IIS.Product_47130.Университет Университет
        {
            get
            {
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Университет Get start)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Университет Get start)
                IIS.Product_47130.Университет result = this.fУниверситет;
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Университет Get end)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Университет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Университет Set start)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Университет Set start)
                this.fУниверситет = value;
                // *** Start programmer edit section *** (ЗаявкаНаЭкскурсию.Университет Set end)

                // *** End programmer edit section *** (ЗаявкаНаЭкскурсию.Университет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаявкаНаЭкскурсиюE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаНаЭкскурсиюE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаНаЭкскурсиюE", typeof(IIS.Product_47130.ЗаявкаНаЭкскурсию));
                }
            }
            
            /// <summary>
            /// "ЗаявкаНаЭкскурсиюL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаявкаНаЭкскурсиюL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаявкаНаЭкскурсиюL", typeof(IIS.Product_47130.ЗаявкаНаЭкскурсию));
                }
            }
        }
    }
}
