//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Курс.
    /// </summary>
    // *** Start programmer edit section *** (Курс CustomAttributes)

    // *** End programmer edit section *** (Курс CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КурсE", new string[] {
            "Название as \'Название\'",
            "Год as \'Год\'",
            "Подготовка as \'Подготовка\'",
            "Университет as \'Университет\'",
            "Университет.Название as \'Название\'"})]
    [View("КурсL", new string[] {
            "Название as \'Название\'",
            "Год as \'Год\'",
            "Подготовка as \'Подготовка\'",
            "Университет.Название as \'Название\'"})]
    public class Курс : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private byte fГод;
        
        private string fПодготовка;
        
        private IIS.Product_47130.Университет fУниверситет;
        
        // *** Start programmer edit section *** (Курс CustomMembers)

        // *** End programmer edit section *** (Курс CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Название CustomAttributes)

        // *** End programmer edit section *** (Курс.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Название Get start)

                // *** End programmer edit section *** (Курс.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Курс.Название Get end)

                // *** End programmer edit section *** (Курс.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Название Set start)

                // *** End programmer edit section *** (Курс.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Курс.Название Set end)

                // *** End programmer edit section *** (Курс.Название Set end)
            }
        }
        
        /// <summary>
        /// Год.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Год CustomAttributes)

        // *** End programmer edit section *** (Курс.Год CustomAttributes)
        public virtual byte Год
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Год Get start)

                // *** End programmer edit section *** (Курс.Год Get start)
                byte result = this.fГод;
                // *** Start programmer edit section *** (Курс.Год Get end)

                // *** End programmer edit section *** (Курс.Год Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Год Set start)

                // *** End programmer edit section *** (Курс.Год Set start)
                this.fГод = value;
                // *** Start programmer edit section *** (Курс.Год Set end)

                // *** End programmer edit section *** (Курс.Год Set end)
            }
        }
        
        /// <summary>
        /// Подготовка.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Подготовка CustomAttributes)

        // *** End programmer edit section *** (Курс.Подготовка CustomAttributes)
        [StrLen(255)]
        public virtual string Подготовка
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Подготовка Get start)

                // *** End programmer edit section *** (Курс.Подготовка Get start)
                string result = this.fПодготовка;
                // *** Start programmer edit section *** (Курс.Подготовка Get end)

                // *** End programmer edit section *** (Курс.Подготовка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Подготовка Set start)

                // *** End programmer edit section *** (Курс.Подготовка Set start)
                this.fПодготовка = value;
                // *** Start programmer edit section *** (Курс.Подготовка Set end)

                // *** End programmer edit section *** (Курс.Подготовка Set end)
            }
        }
        
        /// <summary>
        /// Курс.
        /// </summary>
        // *** Start programmer edit section *** (Курс.Университет CustomAttributes)

        // *** End programmer edit section *** (Курс.Университет CustomAttributes)
        [NotNull()]
        public virtual IIS.Product_47130.Университет Университет
        {
            get
            {
                // *** Start programmer edit section *** (Курс.Университет Get start)

                // *** End programmer edit section *** (Курс.Университет Get start)
                IIS.Product_47130.Университет result = this.fУниверситет;
                // *** Start programmer edit section *** (Курс.Университет Get end)

                // *** End programmer edit section *** (Курс.Университет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Курс.Университет Set start)

                // *** End programmer edit section *** (Курс.Университет Set start)
                this.fУниверситет = value;
                // *** Start programmer edit section *** (Курс.Университет Set end)

                // *** End programmer edit section *** (Курс.Университет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КурсE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КурсE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КурсE", typeof(IIS.Product_47130.Курс));
                }
            }
            
            /// <summary>
            /// "КурсL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КурсL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КурсL", typeof(IIS.Product_47130.Курс));
                }
            }
        }
    }
}
