//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Необходимость практики.
    /// </summary>
    // *** Start programmer edit section *** (НеобходимостьПрактики CustomAttributes)

    // *** End programmer edit section *** (НеобходимостьПрактики CustomAttributes)
    public enum НеобходимостьПрактики
    {
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (НеобходимостьПрактики.НеНужна CustomAttributes)

        // *** End programmer edit section *** (НеобходимостьПрактики.НеНужна CustomAttributes)
        НеНужна,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (НеобходимостьПрактики.Нужна CustomAttributes)

        // *** End programmer edit section *** (НеобходимостьПрактики.Нужна CustomAttributes)
        Нужна,
        
        /// <summary>
        /// 
        /// </summary>
        // *** Start programmer edit section *** (НеобходимостьПрактики.Проходит CustomAttributes)

        // *** End programmer edit section *** (НеобходимостьПрактики.Проходит CustomAttributes)
        Проходит,
    }
}
