//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Представитель компании.
    /// </summary>
    // *** Start programmer edit section *** (ПредставительКомпании CustomAttributes)

    // *** End programmer edit section *** (ПредставительКомпании CustomAttributes)
    [AutoAltered()]
    [Caption("Представитель компании")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПредставительКомпанииE", new string[] {
            "Имя as \'Имя\'",
            "Почта as \'Почта\'",
            "Телефон as \'Телефон\'",
            "Должность as \'Должность\'",
            "РабочаяГруппа as \'Рабочая группа\'",
            "Компания as \'Компания\'",
            "Компания.Название as \'Название\'"})]
    [View("ПредставительКомпанииL", new string[] {
            "Имя as \'Имя\'",
            "Почта as \'Почта\'",
            "Телефон as \'Телефон\'",
            "Должность as \'Должность\'",
            "Компания.Название as \'Название\'"})]
    public class ПредставительКомпании : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        private string fПочта;
        
        private string fТелефон;
        
        private string fДолжность;
        
        private IIS.Product_47130.РабочаяГруппа fРабочаяГруппа;
        
        private IIS.Product_47130.Компания fКомпания;
        
        // *** Start programmer edit section *** (ПредставительКомпании CustomMembers)

        // *** End programmer edit section *** (ПредставительКомпании CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительКомпании.Имя CustomAttributes)

        // *** End programmer edit section *** (ПредставительКомпании.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Имя Get start)

                // *** End programmer edit section *** (ПредставительКомпании.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (ПредставительКомпании.Имя Get end)

                // *** End programmer edit section *** (ПредставительКомпании.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Имя Set start)

                // *** End programmer edit section *** (ПредставительКомпании.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (ПредставительКомпании.Имя Set end)

                // *** End programmer edit section *** (ПредставительКомпании.Имя Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительКомпании.Почта CustomAttributes)

        // *** End programmer edit section *** (ПредставительКомпании.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Почта Get start)

                // *** End programmer edit section *** (ПредставительКомпании.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (ПредставительКомпании.Почта Get end)

                // *** End programmer edit section *** (ПредставительКомпании.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Почта Set start)

                // *** End programmer edit section *** (ПредставительКомпании.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (ПредставительКомпании.Почта Set end)

                // *** End programmer edit section *** (ПредставительКомпании.Почта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительКомпании.Телефон CustomAttributes)

        // *** End programmer edit section *** (ПредставительКомпании.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Телефон Get start)

                // *** End programmer edit section *** (ПредставительКомпании.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (ПредставительКомпании.Телефон Get end)

                // *** End programmer edit section *** (ПредставительКомпании.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Телефон Set start)

                // *** End programmer edit section *** (ПредставительКомпании.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (ПредставительКомпании.Телефон Set end)

                // *** End programmer edit section *** (ПредставительКомпании.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительКомпании.Должность CustomAttributes)

        // *** End programmer edit section *** (ПредставительКомпании.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Должность Get start)

                // *** End programmer edit section *** (ПредставительКомпании.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (ПредставительКомпании.Должность Get end)

                // *** End programmer edit section *** (ПредставительКомпании.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Должность Set start)

                // *** End programmer edit section *** (ПредставительКомпании.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ПредставительКомпании.Должность Set end)

                // *** End programmer edit section *** (ПредставительКомпании.Должность Set end)
            }
        }
        
        /// <summary>
        /// Представитель компании.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительКомпании.РабочаяГруппа CustomAttributes)

        // *** End programmer edit section *** (ПредставительКомпании.РабочаяГруппа CustomAttributes)
        public virtual IIS.Product_47130.РабочаяГруппа РабочаяГруппа
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительКомпании.РабочаяГруппа Get start)

                // *** End programmer edit section *** (ПредставительКомпании.РабочаяГруппа Get start)
                IIS.Product_47130.РабочаяГруппа result = this.fРабочаяГруппа;
                // *** Start programmer edit section *** (ПредставительКомпании.РабочаяГруппа Get end)

                // *** End programmer edit section *** (ПредставительКомпании.РабочаяГруппа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительКомпании.РабочаяГруппа Set start)

                // *** End programmer edit section *** (ПредставительКомпании.РабочаяГруппа Set start)
                this.fРабочаяГруппа = value;
                // *** Start programmer edit section *** (ПредставительКомпании.РабочаяГруппа Set end)

                // *** End programmer edit section *** (ПредставительКомпании.РабочаяГруппа Set end)
            }
        }
        
        /// <summary>
        /// Представитель компании.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительКомпании.Компания CustomAttributes)

        // *** End programmer edit section *** (ПредставительКомпании.Компания CustomAttributes)
        public virtual IIS.Product_47130.Компания Компания
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Компания Get start)

                // *** End programmer edit section *** (ПредставительКомпании.Компания Get start)
                IIS.Product_47130.Компания result = this.fКомпания;
                // *** Start programmer edit section *** (ПредставительКомпании.Компания Get end)

                // *** End programmer edit section *** (ПредставительКомпании.Компания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительКомпании.Компания Set start)

                // *** End programmer edit section *** (ПредставительКомпании.Компания Set start)
                this.fКомпания = value;
                // *** Start programmer edit section *** (ПредставительКомпании.Компания Set end)

                // *** End programmer edit section *** (ПредставительКомпании.Компания Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПредставительКомпанииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредставительКомпанииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредставительКомпанииE", typeof(IIS.Product_47130.ПредставительКомпании));
                }
            }
            
            /// <summary>
            /// "ПредставительКомпанииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредставительКомпанииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредставительКомпанииL", typeof(IIS.Product_47130.ПредставительКомпании));
                }
            }
        }
    }
}
