//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Представитель ОУ.
    /// </summary>
    // *** Start programmer edit section *** (ПредставительОУ CustomAttributes)

    // *** End programmer edit section *** (ПредставительОУ CustomAttributes)
    [AutoAltered()]
    [Caption("Представитель ОУ")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПредставительОУE", new string[] {
            "Имя as \'Имя\'",
            "Почта as \'Почта\'",
            "Телефон as \'Телефон\'",
            "Должность as \'Должность\'",
            "Университет as \'Университет\'",
            "Университет.Название as \'Название\'",
            "РабочаяГруппа as \'Рабочая группа\'"})]
    [View("ПредставительОУL", new string[] {
            "Имя as \'Имя\'",
            "Почта as \'Почта\'",
            "Телефон as \'Телефон\'",
            "Должность as \'Должность\'",
            "Университет.Название as \'Название\'"})]
    public class ПредставительОУ : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        private string fПочта;
        
        private string fТелефон;
        
        private string fДолжность;
        
        private IIS.Product_47130.Университет fУниверситет;
        
        private IIS.Product_47130.РабочаяГруппа fРабочаяГруппа;
        
        // *** Start programmer edit section *** (ПредставительОУ CustomMembers)

        // *** End programmer edit section *** (ПредставительОУ CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Имя CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Имя Get start)

                // *** End programmer edit section *** (ПредставительОУ.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (ПредставительОУ.Имя Get end)

                // *** End programmer edit section *** (ПредставительОУ.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Имя Set start)

                // *** End programmer edit section *** (ПредставительОУ.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (ПредставительОУ.Имя Set end)

                // *** End programmer edit section *** (ПредставительОУ.Имя Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Почта CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Почта Get start)

                // *** End programmer edit section *** (ПредставительОУ.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (ПредставительОУ.Почта Get end)

                // *** End programmer edit section *** (ПредставительОУ.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Почта Set start)

                // *** End programmer edit section *** (ПредставительОУ.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (ПредставительОУ.Почта Set end)

                // *** End programmer edit section *** (ПредставительОУ.Почта Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Телефон CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Телефон CustomAttributes)
        [StrLen(255)]
        public virtual string Телефон
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Телефон Get start)

                // *** End programmer edit section *** (ПредставительОУ.Телефон Get start)
                string result = this.fТелефон;
                // *** Start programmer edit section *** (ПредставительОУ.Телефон Get end)

                // *** End programmer edit section *** (ПредставительОУ.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Телефон Set start)

                // *** End programmer edit section *** (ПредставительОУ.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (ПредставительОУ.Телефон Set end)

                // *** End programmer edit section *** (ПредставительОУ.Телефон Set end)
            }
        }
        
        /// <summary>
        /// Должность.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Должность CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Должность CustomAttributes)
        [StrLen(255)]
        public virtual string Должность
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Должность Get start)

                // *** End programmer edit section *** (ПредставительОУ.Должность Get start)
                string result = this.fДолжность;
                // *** Start programmer edit section *** (ПредставительОУ.Должность Get end)

                // *** End programmer edit section *** (ПредставительОУ.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Должность Set start)

                // *** End programmer edit section *** (ПредставительОУ.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (ПредставительОУ.Должность Set end)

                // *** End programmer edit section *** (ПредставительОУ.Должность Set end)
            }
        }
        
        /// <summary>
        /// Представитель ОУ.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.Университет CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.Университет CustomAttributes)
        public virtual IIS.Product_47130.Университет Университет
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.Университет Get start)

                // *** End programmer edit section *** (ПредставительОУ.Университет Get start)
                IIS.Product_47130.Университет result = this.fУниверситет;
                // *** Start programmer edit section *** (ПредставительОУ.Университет Get end)

                // *** End programmer edit section *** (ПредставительОУ.Университет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.Университет Set start)

                // *** End programmer edit section *** (ПредставительОУ.Университет Set start)
                this.fУниверситет = value;
                // *** Start programmer edit section *** (ПредставительОУ.Университет Set end)

                // *** End programmer edit section *** (ПредставительОУ.Университет Set end)
            }
        }
        
        /// <summary>
        /// Представитель ОУ.
        /// </summary>
        // *** Start programmer edit section *** (ПредставительОУ.РабочаяГруппа CustomAttributes)

        // *** End programmer edit section *** (ПредставительОУ.РабочаяГруппа CustomAttributes)
        public virtual IIS.Product_47130.РабочаяГруппа РабочаяГруппа
        {
            get
            {
                // *** Start programmer edit section *** (ПредставительОУ.РабочаяГруппа Get start)

                // *** End programmer edit section *** (ПредставительОУ.РабочаяГруппа Get start)
                IIS.Product_47130.РабочаяГруппа result = this.fРабочаяГруппа;
                // *** Start programmer edit section *** (ПредставительОУ.РабочаяГруппа Get end)

                // *** End programmer edit section *** (ПредставительОУ.РабочаяГруппа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПредставительОУ.РабочаяГруппа Set start)

                // *** End programmer edit section *** (ПредставительОУ.РабочаяГруппа Set start)
                this.fРабочаяГруппа = value;
                // *** Start programmer edit section *** (ПредставительОУ.РабочаяГруппа Set end)

                // *** End programmer edit section *** (ПредставительОУ.РабочаяГруппа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПредставительОУE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредставительОУE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредставительОУE", typeof(IIS.Product_47130.ПредставительОУ));
                }
            }
            
            /// <summary>
            /// "ПредставительОУL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПредставительОУL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПредставительОУL", typeof(IIS.Product_47130.ПредставительОУ));
                }
            }
        }
    }
}
