//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Рабочая группа.
    /// </summary>
    // *** Start programmer edit section *** (РабочаяГруппа CustomAttributes)

    // *** End programmer edit section *** (РабочаяГруппа CustomAttributes)
    [AutoAltered()]
    [Caption("Рабочая группа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РабочаяГруппаE", new string[0])]
    [View("РабочаяГруппаL", new string[0])]
    public class РабочаяГруппа : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (РабочаяГруппа CustomMembers)

        // *** End programmer edit section *** (РабочаяГруппа CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РабочаяГруппаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РабочаяГруппаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РабочаяГруппаE", typeof(IIS.Product_47130.РабочаяГруппа));
                }
            }
            
            /// <summary>
            /// "РабочаяГруппаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РабочаяГруппаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РабочаяГруппаL", typeof(IIS.Product_47130.РабочаяГруппа));
                }
            }
        }
    }
}
