//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Собрание.
    /// </summary>
    // *** Start programmer edit section *** (Собрание CustomAttributes)

    // *** End programmer edit section *** (Собрание CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СобраниеE", new string[] {
            "Дата as \'Дата\'",
            "Тема as \'Тема\'",
            "РабочаяГруппа as \'Рабочая группа\'"})]
    [View("СобраниеL", new string[] {
            "Дата as \'Дата\'",
            "Тема as \'Тема\'"})]
    public class Собрание : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private string fТема;
        
        private IIS.Product_47130.РабочаяГруппа fРабочаяГруппа;
        
        // *** Start programmer edit section *** (Собрание CustomMembers)

        // *** End programmer edit section *** (Собрание CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Собрание.Дата CustomAttributes)

        // *** End programmer edit section *** (Собрание.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Собрание.Дата Get start)

                // *** End programmer edit section *** (Собрание.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Собрание.Дата Get end)

                // *** End programmer edit section *** (Собрание.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Собрание.Дата Set start)

                // *** End programmer edit section *** (Собрание.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Собрание.Дата Set end)

                // *** End programmer edit section *** (Собрание.Дата Set end)
            }
        }
        
        /// <summary>
        /// Тема.
        /// </summary>
        // *** Start programmer edit section *** (Собрание.Тема CustomAttributes)

        // *** End programmer edit section *** (Собрание.Тема CustomAttributes)
        [StrLen(255)]
        public virtual string Тема
        {
            get
            {
                // *** Start programmer edit section *** (Собрание.Тема Get start)

                // *** End programmer edit section *** (Собрание.Тема Get start)
                string result = this.fТема;
                // *** Start programmer edit section *** (Собрание.Тема Get end)

                // *** End programmer edit section *** (Собрание.Тема Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Собрание.Тема Set start)

                // *** End programmer edit section *** (Собрание.Тема Set start)
                this.fТема = value;
                // *** Start programmer edit section *** (Собрание.Тема Set end)

                // *** End programmer edit section *** (Собрание.Тема Set end)
            }
        }
        
        /// <summary>
        /// Собрание.
        /// </summary>
        // *** Start programmer edit section *** (Собрание.РабочаяГруппа CustomAttributes)

        // *** End programmer edit section *** (Собрание.РабочаяГруппа CustomAttributes)
        public virtual IIS.Product_47130.РабочаяГруппа РабочаяГруппа
        {
            get
            {
                // *** Start programmer edit section *** (Собрание.РабочаяГруппа Get start)

                // *** End programmer edit section *** (Собрание.РабочаяГруппа Get start)
                IIS.Product_47130.РабочаяГруппа result = this.fРабочаяГруппа;
                // *** Start programmer edit section *** (Собрание.РабочаяГруппа Get end)

                // *** End programmer edit section *** (Собрание.РабочаяГруппа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Собрание.РабочаяГруппа Set start)

                // *** End programmer edit section *** (Собрание.РабочаяГруппа Set start)
                this.fРабочаяГруппа = value;
                // *** Start programmer edit section *** (Собрание.РабочаяГруппа Set end)

                // *** End programmer edit section *** (Собрание.РабочаяГруппа Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СобраниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СобраниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СобраниеE", typeof(IIS.Product_47130.Собрание));
                }
            }
            
            /// <summary>
            /// "СобраниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СобраниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СобраниеL", typeof(IIS.Product_47130.Собрание));
                }
            }
        }
    }
}
