//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Студент.
    /// </summary>
    // *** Start programmer edit section *** (Студент CustomAttributes)

    // *** End programmer edit section *** (Студент CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтудентE", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Практика as \'Практика\'",
            "ЗаявкаНаПрактику as \'Заявка на практику\'",
            "ЗаявкаНаПрактику.Информация as \'Информация\'",
            "Курс as \'Курс\'",
            "Курс.Название as \'Название\'",
            "Практика as \'Практика\'",
            "Практика.Информация as \'Информация\'"})]
    [View("СтудентL", new string[] {
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Практика as \'Практика\'",
            "ЗаявкаНаПрактику.Информация as \'Информация\'",
            "Курс.Название as \'Название\'",
            "Практика.Информация as \'Информация\'"})]
    public class Студент : ICSSoft.STORMNET.DataObject
    {
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private string fПодготовка;
        
        private IIS.Product_47130.НеобходимостьПрактики fСтатусПрактики;
        
        private IIS.Product_47130.ЗаявкаНаПрактику fЗаявкаНаПрактику;
        
        private IIS.Product_47130.Курс fКурс;
        
        private IIS.Product_47130.Практика fПрактика;
        
        // *** Start programmer edit section *** (Студент CustomMembers)

        // *** End programmer edit section *** (Студент CustomMembers)

        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Фамилия CustomAttributes)

        // *** End programmer edit section *** (Студент.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Фамилия Get start)

                // *** End programmer edit section *** (Студент.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (Студент.Фамилия Get end)

                // *** End programmer edit section *** (Студент.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Фамилия Set start)

                // *** End programmer edit section *** (Студент.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (Студент.Фамилия Set end)

                // *** End programmer edit section *** (Студент.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Имя CustomAttributes)

        // *** End programmer edit section *** (Студент.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Имя Get start)

                // *** End programmer edit section *** (Студент.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Студент.Имя Get end)

                // *** End programmer edit section *** (Студент.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Имя Set start)

                // *** End programmer edit section *** (Студент.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Студент.Имя Set end)

                // *** End programmer edit section *** (Студент.Имя Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Отчество CustomAttributes)

        // *** End programmer edit section *** (Студент.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Отчество Get start)

                // *** End programmer edit section *** (Студент.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (Студент.Отчество Get end)

                // *** End programmer edit section *** (Студент.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Отчество Set start)

                // *** End programmer edit section *** (Студент.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (Студент.Отчество Set end)

                // *** End programmer edit section *** (Студент.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Подготовка.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Подготовка CustomAttributes)

        // *** End programmer edit section *** (Студент.Подготовка CustomAttributes)
        [StrLen(255)]
        public virtual string Подготовка
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Подготовка Get start)

                // *** End programmer edit section *** (Студент.Подготовка Get start)
                string result = this.fПодготовка;
                // *** Start programmer edit section *** (Студент.Подготовка Get end)

                // *** End programmer edit section *** (Студент.Подготовка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Подготовка Set start)

                // *** End programmer edit section *** (Студент.Подготовка Set start)
                this.fПодготовка = value;
                // *** Start programmer edit section *** (Студент.Подготовка Set end)

                // *** End programmer edit section *** (Студент.Подготовка Set end)
            }
        }
        
        /// <summary>
        /// СтатусПрактики.
        /// </summary>
        // *** Start programmer edit section *** (Студент.СтатусПрактики CustomAttributes)

        // *** End programmer edit section *** (Студент.СтатусПрактики CustomAttributes)
        public virtual IIS.Product_47130.НеобходимостьПрактики СтатусПрактики
        {
            get
            {
                // *** Start programmer edit section *** (Студент.СтатусПрактики Get start)

                // *** End programmer edit section *** (Студент.СтатусПрактики Get start)
                IIS.Product_47130.НеобходимостьПрактики result = this.fСтатусПрактики;
                // *** Start programmer edit section *** (Студент.СтатусПрактики Get end)

                // *** End programmer edit section *** (Студент.СтатусПрактики Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.СтатусПрактики Set start)

                // *** End programmer edit section *** (Студент.СтатусПрактики Set start)
                this.fСтатусПрактики = value;
                // *** Start programmer edit section *** (Студент.СтатусПрактики Set end)

                // *** End programmer edit section *** (Студент.СтатусПрактики Set end)
            }
        }
        
        /// <summary>
        /// Студент.
        /// </summary>
        // *** Start programmer edit section *** (Студент.ЗаявкаНаПрактику CustomAttributes)

        // *** End programmer edit section *** (Студент.ЗаявкаНаПрактику CustomAttributes)
        public virtual IIS.Product_47130.ЗаявкаНаПрактику ЗаявкаНаПрактику
        {
            get
            {
                // *** Start programmer edit section *** (Студент.ЗаявкаНаПрактику Get start)

                // *** End programmer edit section *** (Студент.ЗаявкаНаПрактику Get start)
                IIS.Product_47130.ЗаявкаНаПрактику result = this.fЗаявкаНаПрактику;
                // *** Start programmer edit section *** (Студент.ЗаявкаНаПрактику Get end)

                // *** End programmer edit section *** (Студент.ЗаявкаНаПрактику Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.ЗаявкаНаПрактику Set start)

                // *** End programmer edit section *** (Студент.ЗаявкаНаПрактику Set start)
                this.fЗаявкаНаПрактику = value;
                // *** Start programmer edit section *** (Студент.ЗаявкаНаПрактику Set end)

                // *** End programmer edit section *** (Студент.ЗаявкаНаПрактику Set end)
            }
        }
        
        /// <summary>
        /// Студент.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Курс CustomAttributes)

        // *** End programmer edit section *** (Студент.Курс CustomAttributes)
        [NotNull()]
        public virtual IIS.Product_47130.Курс Курс
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Курс Get start)

                // *** End programmer edit section *** (Студент.Курс Get start)
                IIS.Product_47130.Курс result = this.fКурс;
                // *** Start programmer edit section *** (Студент.Курс Get end)

                // *** End programmer edit section *** (Студент.Курс Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Курс Set start)

                // *** End programmer edit section *** (Студент.Курс Set start)
                this.fКурс = value;
                // *** Start programmer edit section *** (Студент.Курс Set end)

                // *** End programmer edit section *** (Студент.Курс Set end)
            }
        }
        
        /// <summary>
        /// Студент.
        /// </summary>
        // *** Start programmer edit section *** (Студент.Практика CustomAttributes)

        // *** End programmer edit section *** (Студент.Практика CustomAttributes)
        public virtual IIS.Product_47130.Практика Практика
        {
            get
            {
                // *** Start programmer edit section *** (Студент.Практика Get start)

                // *** End programmer edit section *** (Студент.Практика Get start)
                IIS.Product_47130.Практика result = this.fПрактика;
                // *** Start programmer edit section *** (Студент.Практика Get end)

                // *** End programmer edit section *** (Студент.Практика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Студент.Практика Set start)

                // *** End programmer edit section *** (Студент.Практика Set start)
                this.fПрактика = value;
                // *** Start programmer edit section *** (Студент.Практика Set end)

                // *** End programmer edit section *** (Студент.Практика Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтудентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтудентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтудентE", typeof(IIS.Product_47130.Студент));
                }
            }
            
            /// <summary>
            /// "СтудентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтудентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтудентL", typeof(IIS.Product_47130.Студент));
                }
            }
        }
    }
}
