//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Университет.
    /// </summary>
    // *** Start programmer edit section *** (Университет CustomAttributes)

    // *** End programmer edit section *** (Университет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УниверситетE", new string[] {
            "Название as \'Название\'",
            "Информация as \'Информация\'",
            "Ссылка as \'Ссылка\'"})]
    [View("УниверситетL", new string[] {
            "Название as \'Название\'",
            "Информация as \'Информация\'",
            "Ссылка as \'Ссылка\'"})]
    public class Университет : ICSSoft.STORMNET.DataObject
    {
        
        private string fНазвание;
        
        private string fИнформация;
        
        private string fСсылка;
        
        // *** Start programmer edit section *** (Университет CustomMembers)

        // *** End programmer edit section *** (Университет CustomMembers)

        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Университет.Название CustomAttributes)

        // *** End programmer edit section *** (Университет.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Университет.Название Get start)

                // *** End programmer edit section *** (Университет.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Университет.Название Get end)

                // *** End programmer edit section *** (Университет.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Университет.Название Set start)

                // *** End programmer edit section *** (Университет.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Университет.Название Set end)

                // *** End programmer edit section *** (Университет.Название Set end)
            }
        }
        
        /// <summary>
        /// Информация.
        /// </summary>
        // *** Start programmer edit section *** (Университет.Информация CustomAttributes)

        // *** End programmer edit section *** (Университет.Информация CustomAttributes)
        [StrLen(255)]
        public virtual string Информация
        {
            get
            {
                // *** Start programmer edit section *** (Университет.Информация Get start)

                // *** End programmer edit section *** (Университет.Информация Get start)
                string result = this.fИнформация;
                // *** Start programmer edit section *** (Университет.Информация Get end)

                // *** End programmer edit section *** (Университет.Информация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Университет.Информация Set start)

                // *** End programmer edit section *** (Университет.Информация Set start)
                this.fИнформация = value;
                // *** Start programmer edit section *** (Университет.Информация Set end)

                // *** End programmer edit section *** (Университет.Информация Set end)
            }
        }
        
        /// <summary>
        /// Ссылка.
        /// </summary>
        // *** Start programmer edit section *** (Университет.Ссылка CustomAttributes)

        // *** End programmer edit section *** (Университет.Ссылка CustomAttributes)
        [StrLen(255)]
        public virtual string Ссылка
        {
            get
            {
                // *** Start programmer edit section *** (Университет.Ссылка Get start)

                // *** End programmer edit section *** (Университет.Ссылка Get start)
                string result = this.fСсылка;
                // *** Start programmer edit section *** (Университет.Ссылка Get end)

                // *** End programmer edit section *** (Университет.Ссылка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Университет.Ссылка Set start)

                // *** End programmer edit section *** (Университет.Ссылка Set start)
                this.fСсылка = value;
                // *** Start programmer edit section *** (Университет.Ссылка Set end)

                // *** End programmer edit section *** (Университет.Ссылка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УниверситетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УниверситетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УниверситетE", typeof(IIS.Product_47130.Университет));
                }
            }
            
            /// <summary>
            /// "УниверситетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УниверситетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УниверситетL", typeof(IIS.Product_47130.Университет));
                }
            }
        }
    }
}
