//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Product_47130
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Экскурсия.
    /// </summary>
    // *** Start programmer edit section *** (Экскурсия CustomAttributes)

    // *** End programmer edit section *** (Экскурсия CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЭкскурсияE", new string[] {
            "Дата as \'Дата\'",
            "Количество as \'Количество\'",
            "Состояние as \'Состояние\'",
            "Компания as \'Компания\'",
            "Компания.Название as \'Название\'"})]
    [View("ЭкскурсияL", new string[] {
            "Дата as \'Дата\'",
            "Количество as \'Количество\'",
            "Состояние as \'Состояние\'",
            "Компания.Название as \'Название\'"})]
    public class Экскурсия : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private byte fКоличество;
        
        private IIS.Product_47130.СостояниеМероприятия fСостояние;
        
        private IIS.Product_47130.Компания fКомпания;
        
        // *** Start programmer edit section *** (Экскурсия CustomMembers)

        // *** End programmer edit section *** (Экскурсия CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Экскурсия.Дата CustomAttributes)

        // *** End programmer edit section *** (Экскурсия.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Экскурсия.Дата Get start)

                // *** End programmer edit section *** (Экскурсия.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Экскурсия.Дата Get end)

                // *** End programmer edit section *** (Экскурсия.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Экскурсия.Дата Set start)

                // *** End programmer edit section *** (Экскурсия.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Экскурсия.Дата Set end)

                // *** End programmer edit section *** (Экскурсия.Дата Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (Экскурсия.Количество CustomAttributes)

        // *** End programmer edit section *** (Экскурсия.Количество CustomAttributes)
        public virtual byte Количество
        {
            get
            {
                // *** Start programmer edit section *** (Экскурсия.Количество Get start)

                // *** End programmer edit section *** (Экскурсия.Количество Get start)
                byte result = this.fКоличество;
                // *** Start programmer edit section *** (Экскурсия.Количество Get end)

                // *** End programmer edit section *** (Экскурсия.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Экскурсия.Количество Set start)

                // *** End programmer edit section *** (Экскурсия.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (Экскурсия.Количество Set end)

                // *** End programmer edit section *** (Экскурсия.Количество Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (Экскурсия.Состояние CustomAttributes)

        // *** End programmer edit section *** (Экскурсия.Состояние CustomAttributes)
        public virtual IIS.Product_47130.СостояниеМероприятия Состояние
        {
            get
            {
                // *** Start programmer edit section *** (Экскурсия.Состояние Get start)

                // *** End programmer edit section *** (Экскурсия.Состояние Get start)
                IIS.Product_47130.СостояниеМероприятия result = this.fСостояние;
                // *** Start programmer edit section *** (Экскурсия.Состояние Get end)

                // *** End programmer edit section *** (Экскурсия.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Экскурсия.Состояние Set start)

                // *** End programmer edit section *** (Экскурсия.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (Экскурсия.Состояние Set end)

                // *** End programmer edit section *** (Экскурсия.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Экскурсия.
        /// </summary>
        // *** Start programmer edit section *** (Экскурсия.Компания CustomAttributes)

        // *** End programmer edit section *** (Экскурсия.Компания CustomAttributes)
        public virtual IIS.Product_47130.Компания Компания
        {
            get
            {
                // *** Start programmer edit section *** (Экскурсия.Компания Get start)

                // *** End programmer edit section *** (Экскурсия.Компания Get start)
                IIS.Product_47130.Компания result = this.fКомпания;
                // *** Start programmer edit section *** (Экскурсия.Компания Get end)

                // *** End programmer edit section *** (Экскурсия.Компания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Экскурсия.Компания Set start)

                // *** End programmer edit section *** (Экскурсия.Компания Set start)
                this.fКомпания = value;
                // *** Start programmer edit section *** (Экскурсия.Компания Set end)

                // *** End programmer edit section *** (Экскурсия.Компания Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЭкскурсияE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭкскурсияE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭкскурсияE", typeof(IIS.Product_47130.Экскурсия));
                }
            }
            
            /// <summary>
            /// "ЭкскурсияL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭкскурсияL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭкскурсияL", typeof(IIS.Product_47130.Экскурсия));
                }
            }
        }
    }
}
